cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index),
    # path('basket-page', views.basket_page)
    path('<slug:category_slug>/', views.index,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.index,
         name='product_detail')
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

pizzashop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('mainapp.urls', namespace='pshop')),
]

cart/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pshop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image_url = models.CharField(max_length=1000, blank=True)
    description = models.TextField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('pshop:product_detail', args=[self.id, self.slug])

orders/models.py
from django.db import models
from mainapp.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):

    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)

    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)


orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mainapp.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    print(request.POST['update'])
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    if request.POST['update'] == 'True':
        return redirect('cart:cart_detail')
    else:
        return redirect('/')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


# Create your views here.
def index(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    cart_product_form = CartAddProductForm()
    return render(request, 'mainapp/index.html', {
                      'categories': categories,
                      'products': products,
                      'cart_product_form': cart_product_form,
                  })


# def basket_page(request):
#     return render(request, 'mainapp/basket_page.html')

# from django.shortcuts import render, get_object_or_404
# from .models import Category, Product
#
#
# def product_list(request, category_slug=None):
#     category = None
#     categories = Category.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         category = get_object_or_404(Category, slug=category_slug)
#         products = products.filter(category=category)
#     return render(request, 'shop/product/list.html',
#                   {
#                       'category': category,
#                       'categories': categories,
#                       'products': products
#                   })
#
#
# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#     return render(request, 'shop/product/detail.html', {'product': product})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            return render(request,
                          'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})

mainapp/templates/cart/det.html
{% extends "mainapp/base.html" %}

{% block title %}
  Корзина
{% endblock %}

{% block solid %}
<div>
    <style>
        details {
            display: flex;
            flex-direction: column;
            flex-wrap: wrap;
        }
        detail {
            display: flex;
            flex-direction: row;
        }
        .heading{
            font-family: Open Sans;
            font-size: 20px;
            font-weight: bold;
            color: #000000;
        }
        .description{
            font-family: Open Sans;
            font-size: 12px;
            font-weight: 100;
            color: #757575;
        }
    </style>

    <details>
        <detail>
          <det>Картинка</det>
          <det>Товар</det>
          <det>Обновить кол-во</det>
          <det>Удалить</det>
          <det>Кол-во</det>
          <det>Цена за шт</det>
          <det>Общая стоимость</det>
        </detail>
        {% for item in cart %}
            {% with product=item.product %}
            <detail>
                <det>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image_url }}"
                        width="100px" height="100px" alt="">
                    </a>
                </det>
                <det>
                    {{ product.name }}
                </det>
                <det>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Обновить цену">
                        {% csrf_token %}
                    </form>
                </det>
                <det>
                    <form action="{% url 'cart:cart_remove' product.id %}">
                        <button>
                            Удалить
                        </button>
                    </form>
                </det>
                <det>
                    {{ item.quantity }}
                </det>
                <det>{{ item.price }}р</det>
                <det>{{ item.total_price }}р</det>
              </detail>
            {% endwith %}
        {% endfor %}
    </details>
</div>
{% endblock %}
<style>
  tbody {background:white}
</style>
  <table>
    <thead>
      <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image_url }}"
                width="100px" height="100px" alt="">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <button style="margin: 10px;
		    padding: 5px;
		    border: 1px solid black;
		    border-radius: 20px;">
		    Обновить цену
            	</button>
                {% csrf_token %}
              </form>
            </td>
            <td>
            <form action="{% url 'cart:cart_remove' product.id %}">
              <button style="margin: 10px;
		    padding: 5px;
		    border: 1px solid black;
		    border-radius: 20px;">
                Удалить
              </button>
            </form>
            </td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">{{ item.price }}р</td>
            <td class="num">{{ item.total_price }}р</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всего</td>
        <td colspan="5"></td>
        <td class="num">{{ cart.get_total_price }}р</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="#" class="button">Оформить заказ</a>
  </p>

mainapp/templates/cart/detail.html
{% extends "mainapp/base.html" %}

{% block title %}
  Корзина
{% endblock %}

{% block solid %}
<div>
    <style>
        detai {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            width: 100%;
        }
        detail {
            display: flex;
            flex-direction: row;
            margin: 10px;
            padding: 15px;
            border: 1px solid black;
            border-radius: 20px;
            background: white;
            justify-content: space-around;
            align-content: stretch;
            width: 100%;
        }
        det {
            margin: 10px;
            width: 50px;
            padding: 15px;

            }
        .heading{
            font-family: Open Sans;
            font-size: 20px;
            font-weight: bold;
            color: #000000;
        }
        .description{
            font-family: Open Sans;
            font-size: 12px;
            font-weight: 100;
            color: #757575;
        }
    </style>

    <detai>
        <detail>
          <det>Картинка</det>
          <det>Товар</det>
          <det>Обновить количество</det>
          <det>Удалить</det>
<!--          <det>Кол-во</det>-->
          <det>Цена за шт</det>
          <det>Общая стоимость</det>
        </detail>
        {% for item in cart %}
            {% with product=item.product %}
            <detail>
                <det>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image_url }}"
                        width="100px" height="100px" alt="">
                    </a>
                </det>
                <det>
                    {{ product.name }}
                </det>
                <det>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <button style="margin: 10px;
		    padding: 5px;
		    border: 1px solid black;
		    border-radius: 20px;">
		    Обновить цену
            	</button>
                {% csrf_token %}
              </form>
                </det>
                <det>
                    <form action="{% url 'cart:cart_remove' product.id %}">
                        {% csrf_token %}
                        <button style="margin: 10px;
		    padding: 5px;
		    border: 1px solid black;
		    border-radius: 20px;">
                            Удалить
                        </button>
                    </form>
                </det>
<!--                <det>-->
<!--                    {{ item.quantity }}-->
<!--                </det>-->
                <det>{{ item.price }}р</det>
                <det>{{ item.total_price }}р</det>
              </detail>
            {% endwith %}
        {% endfor %}
    </detai>
    <form action="{% url 'orders:order_create' %}">
    	<button style="margin: 10px;
            padding: 15px;
            border: 1px solid black;
            border-radius: 20px;">
    		Заказать
    	</button>
    </form>
</div>

{% endblock %}

mainapp/templates/mainapp/base.html
<!doctype html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300" rel="stylesheet" type="text/css">
        <title>{% block title %}{% endblock %}</title>
        <style>
            grandperents {
                display: flex;
                flex-direction: column;
                background: url(https://github.com/yodo-im/python_pizza/blob/main/fon/fon.jpg?raw=true);
            }
            perents {
                height: 200px;
                flex: 1;
            }
            body {
                margin: 0px;
                width: 1010px;
                margin-left: auto;
                margin-right: auto;
            }
            h1, text {
                color: white;
            }

        </style>
    </head>
    <body>
        <grandperents>

            <perents>
                {% include 'mainapp/headers.html' %}
            </perents>

            <perents style="height: 400px;">
                {% block solid %}{% endblock %}
            </perents>

            <perents>
                {% include 'mainapp/footer.html' %}
            </perents>

        </grandperents>
    </body>
</html>

mainapp/templates/mainapp/basket_page.html
{% extends 'mainapp/base.html' %}


{% block title %}
Корзина
{% endblock %}


{% block solid %}
    <div>
        <style>
        baskets {
            display: flex;
            flex-wrap: wrap;
            flex-direction: raw;
            padding: 0;
            margin: 0;
            position: relative;
            width: 1240px;
            left:10px;
        }
        product {
            padding: 5px;
            margin: 0;
            width:  300px;
            height: 500px;
        }
    </style>

        <baskets>
            <product>
                <h1>
                    Корзина
                </h1>
            </product>
        </baskets>
    </div>
{% endblock %}

mainapp/templates/mainapp/footer.html
<div>
    <style>
        parent {
            display: flex;
            flex-direction: row;
            height: 100px;
            align-items: center;
        }
        child {
            padding: 10px;
            margin: 10px;
            flex: 33%;
        }
    </style>

    <parent>
        <child>
            <text>
                Python pizza | 2021
            </text>
        </child>

        <child>
            {% include 'mainapp/messegers.html' %}
        </child>

        <child align="right">
            <text>
                Тел.: 8-800-xxx-xx-xx
            </text>
        </child>
    </parent>
</div>

mainapp/templates/mainapp/headers.html
<!--<div>-->

<!--    <h1>-->
<!--        Python pizza-->
<!--    </h1>-->

<!--    <form action="/">-->
<!--        <button style="position: absolute; right: 120px; top: 35px;">-->
<!--            <basket>-->
<!--                Главная-->
<!--            </basket>-->
<!--        </button>-->
<!--    </form>-->

<!--    <form action="basket-page">-->
<!--        <button style="position: absolute; right: 20px; top: 35px;">-->
<!--            <basket>-->
<!--                Корзина-->
<!--            </basket>-->
<!--        </button>-->
<!--    </form>-->

<!--</div>-->
<div>
    <style>
        headers {
            display: flex;
            flex-direction: row;
            height: 100px;
            align-items: center;
        }
        header {
            padding: 10px;
            margin: 10px;
        }
    </style>

    <headers>
        <header style="width: 500px">
            <h1>
                Python pizza
            </h1>
        </header>

        <header>
            <text>
                Пн-Вс с 7.00 до 23.00 <br>
                Тел.: 8-800-xxx-xx-xx
            </text>
        </header>

        <header>
            <form action="/">
                <button style="margin: 10px;
            padding: 5px;
            border: 1px solid black;
            border-radius: 20px;">
                    <basket>
                        Главная
                    </basket>
                </button>
            </form>
        </header>

        <header>
            <form action="cart">
                <button style="margin: 10px;
            padding: 5px;
            border: 1px solid black;
            border-radius: 20px;">
                    <basket>
                        Корзина<br>{{ cart.get_total_price }}p
                    </basket>
                </button>
            </form>
        </header>

    </headers>
</div>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}


{% block title %}
Python pizza
{% endblock %}


{% block solid %}
{% include 'mainapp/solid.html' %}
{% endblock %}

mainapp/templates/mainapp/messegers.html
<div>
    <style>
        messegers {
            display: flex;
            flex-direction: row;
            justify-content: space-around;
        }
        messeger {
            width:  30px;
            height: 30px;
            margin: 10px;
        }
    </style>
    <messegers>
<!--Vkontakte-->
        <messeger>
            <center>
                <a href="">
                    <img src="https://github.com/yodo-im/python_pizza/blob/main/messeger/Vk.png?raw=true"
                         width="30px" height="30px" alt="Vk">
                </a>
            </center>
        </messeger>
<!--Facebook-->
        <messeger>
            <center>
                <a href="">
                    <img src="https://github.com/yodo-im/python_pizza/blob/main/messeger/Facebook.png?raw=true"
                         width="30px" height="30px" alt="Vk">
                </a>
            </center>
        </messeger>
<!--Google-plus-->
        <messeger>
            <center>
                <a href="">
                    <img src="https://github.com/yodo-im/python_pizza/blob/main/messeger/Google-plus.png?raw=true"
                         width="30px" height="30px" alt="Vk">
                </a>
            </center>
        </messeger>
<!--Instagram-->
        <messeger>
            <center>
                <a href="">
                    <img src="https://github.com/yodo-im/python_pizza/blob/main/messeger/Instagram.png?raw=true"
                         width="30px" height="30px" alt="Vk">
                </a>
            </center>
        </messeger>
<!--Odnoclasniki-->
        <messeger>
            <center>
                <a href="">
                    <img src="https://github.com/yodo-im/python_pizza/blob/main/messeger/Odnoclasniki.png?raw=true"
                         width="30px" height="30px" alt="Vk">
                </a>
            </center>
        </messeger>
    </messegers>
</div>

mainapp/templates/mainapp/pizza.html
<div>
    <style>
        dough {
            display: flex;
            flex-direction: column;
            flex-wrap: wrap;
        }
        .heading{
            font-family: Open Sans;
            font-size: 20px;
            font-weight: bold;
            color: #000000;
        }
        .description{
            font-family: Open Sans;
            font-size: 12px;
            font-weight: 100;
            color: #757575;
        }
    </style>

    <dough>
<!--            Изображение-->
        <filling>
            <img src="{{ product.image_url }}"
                 width="200px" height="200px" alt="" style="position:relative; left: 5px;">
        </filling>
<!--            Название-->
        <filling>
        	<text class="heading">
                    {{ product.name }}
                </text>
        </filling>
<!--            Описание-->
        <filling style="height: 100px">
            <text class="description">
                {{ product.description }}
            </text>
        </filling>
        <filling>
<!--            Цена-->
            <h7>
                {{ product.price }}р
            </h7>
<!--            Кнопка покупки-->
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <button style="position:relative; left:10px;margin: 10px;
            padding: 5px;
            border: 1px solid black;
            border-radius: 20px;">
                    Заказать
                </button>
            </form>
        </filling>
    </dough>
</div>

mainapp/templates/mainapp/pizzas.html
<div>
    <style>
        pizzas {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }
        pizza {
            margin: 10px;
            width: 200px;
            padding: 15px;
            border: 1px solid black;
            border-radius: 20px;
            background: white;
        }
    </style>
    	{% for category in categories %}
	    <pizzas>
		{% for product in products %}
			{% if product.category == category %}
				<pizza>
				    {% include 'mainapp/pizza.html' %}
				</pizza>
			{% endif %}
		{% endfor %}
		
	    </pizzas>
	{% endfor %}
</div>

mainapp/templates/mainapp/solid.html
<div>
    <style>
        corpus {
            display: flex;
            flex-direction: column;
        }
        parts {

        }
    </style>

    <corpus>
        <parts>
            {% include 'mainapp/banner.html' %}
        </parts>

        <parts>
            {% include 'mainapp/pizzas.html' %}
        </parts>
    </corpus>
</div>

mainapp/templates/orders/order/create.html
{% extends "mainapp/base.html" %}

{% block title %}
  Оформление заказа
{% endblock %}

{% block solid %}
<div>
    <style>
        creates {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            height: 400px;
            width: 100%;
        }
        create {
            display: flex;
            flex-direction: column;
            margin: 10px;
            padding: 15px;
            border: 1px solid black;
            border-radius: 20px;
            background: white;
            justify-content: space-around;
            align-content: stretch;
        }
        creat {
        }
    </style>

    <created>
        <create>
            <center>
                <h4>Оформление заказа</h4>
            </center>
        </create>
        <create>
        <div class="order-info">
            <h3>Ваш заказ</h3>
            <ul>
                {% for item in cart %}
                    <li>
                        {{ item.quantity }}x {{ item.product.name }}
                        <span>{{ item.total_price }}р</span>
                    </li>
                {% endfor %}
            </ul>
            <p>Всего: {{ cart.get_total_price }}р</p>
        </div>
        </create>
        <create>
            <form method="post">
                <creat>
                    {{ form.as_p }}
                </creat>
                <button style="margin: 10px;
		    padding: 5px;
		    border: 1px solid black;
		    border-radius: 20px;">
		    Оформить заказ
		</button>
                {% csrf_token %}
            </form>
        </create>
    </created>
</div>

{% endblock %}

mainapp/templates/orders/order/created.html
{% extends "mainapp/base.html" %}

{% block title %}
  Спасибо!
{% endblock %}

{% block solid %}
<div>
    <style>
        sucsess {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            height: 400px;
            width: 100%;
        }
        sucses {
            display: flex;
            flex-direction: column;
            margin: 10px;
            padding: 15px;
            border: 1px solid black;
            border-radius: 20px;
            background: white;
            justify-content: space-around;
            align-content: stretch;
            width: 100%;
        }
        det {
            margin: 10px;
            width: 50px;
            padding: 15px;
            }
    </style>

    <sucsess>
        <sucses>
            <center>
                <h4>Спасибо за заказ!</h4>
                <p>Ваш заказ успешно оформлен. Номер Вашего заказа
                <strong>{{ order.id }}</strong>.</p>
            </center>
        </sucses>
    </sucsess>
</div>

{% endblock %}